Handle runtime port disconnection and reconnect if needed.
MasterOdin/salr-redux pull request #104
Opened 2023-05-21 21:26 UTC by LoneBoco

This should probably work.  I verified it worked in Edge but I was not able to check Firefox.

2023-05-23 20:13 UTC, MasterOdin commented
Just wanted to say thanks for posting this, it'll probably be a week before I get to this having caught and feeling awful with COVID.

2023-05-23 23:12 UTC, LoneBoco commented
I just tested with Firefox and it worked as intended.

2023-08-14 21:11 UTC, MasterOdin requested changes
Sorry for the FAR too long delay on getting this reviewed! COVID, and then a long sabbatical, and this totally fell off my radar.

I appreciate the PR, and I've just got some minor comments, after which I think should be good to merge. Let me know if my comments make sense.

2023-08-14 21:11 UTC, MasterOdin commented on extension/js/background.js
> +        salr_client = false;
Can remove this I think. No matter how many times we re setup the port, the instantiated `SALR` class should be essentially the same as neither `data` nor `chrome.extension.getURL("images/")` should change. Additionally, it leverages the `postMessage` function so it doesn't have an explicit binding to the port we make, so even if the definition for `port` changes, it doesn't really matter.

If we did want to reset `SALR` each time to a fresh instance, would have to do `port.postMessage({'message': 'GetPageSettings'})` as we rely on its response to set `data` for `SALR`, and again, that just seems like wasted overhead.

2023-08-14 21:11 UTC, MasterOdin commented on extension/js/background.js
> +    });
Given the other review comment, I'd actually move this listener outside of this function altogether and only bind it to the initial value of `port` as it should live long enough to get the response back from SALR, and that would give slightly less overhead on any additional ports we create. On that vein, I'd actually maybe rework it to be:

```
var port = createPort();
p.onMessage.addListener(function init(data) {
  salr_client = new SALR(data, chrome.extension.getURL("images/"));
  p.onMessage.removeListener(init);
});
```
where once we initialize `salr_client` variable, we can just rid of the listener altogether on the original instance, and also get rid of the `if` statement that was inside of it.

Thoughts?

2023-08-15 01:03 UTC, LoneBoco commented
I've made some alterations based on your review.  `salr_client` is only created once, when we get the settings.  I also added some more code comments.

2023-08-15 01:20 UTC, MasterOdin approved these changes

2023-08-15 01:20 UTC, MasterOdin commented
Thanks for the PR!

2023-08-15 01:21 UTC, merged